
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.17.2"
  project_id                    = "adcfood4"
  location                      = "us-central1"
  service_name                  = "fe-ai-2003"
  containers                    = [{"container_image" = "gcr.io/design-center-container-repo/gen-ai-rag-fe:latest-03012025", "container_name" = "service-container", "env_vars" = {"retrieval_service_SERVICE_ENDPOINT" = module.retrieval-service.service_uri}, "ports" = {"container_port" = 8080, "name" = "http1"}, "resources" = {"startup_cpu_boost" = false, "cpu_idle" = true}}]
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/aiplatform.user", "roles/run.invoker"])
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  providers                     = { google = google.frontend-service, google-beta = google-beta.frontend-service }
  depends_on                    = [module.project-services-adcfood4]
}
module "retrieval-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.17.2"
  project_id                    = "adcfood4"
  location                      = "us-central1"
  service_name                  = "rs-2003-1"
  containers                    = [{"startup_probe" = {"http_get" = {"path" = "/data/import"}, "initial_delay_seconds" = 30, "period_seconds" = 20, "timeout_seconds" = 15, "failure_threshold" = 10}, "volume_mounts" = [{"mount_path" = "/cloudsql", "name" = "cloudsql"}], "container_image" = "gcr.io/design-center-container-repo/gen-ai-rag-retrieval-service:latest-04022025", "container_name" = "service-container", "env_secret_vars" = {"secret_manager_SECRET" = module.secret-manager.env_vars.SECRET}, "env_vars" = merge({"database_postgresql_CLOUD_SQL_DATABASE_NAME" = module.database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME, "database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.database-postgresql.instance_connection_name, "database_postgresql_CLOUD_SQL_DATABASE_HOST" = module.database-postgresql.instance_first_ip_address}, {"APP_HOST" = "0.0.0.0", "APP_PORT" = "8080", "DB_KIND" = "cloudsql-postgres"}), "ports" = {"container_port" = 8080, "name" = "http1"}, "resources" = {"cpu_idle" = true, "startup_cpu_boost" = false}}]
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client", "roles/secretmanager.secretAccessor", "roles/aiplatform.user"])
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  volumes                       = [{"name" = "cloudsql", "cloud_sql_instance" = {"instances" = [module.database-postgresql.instance_connection_name]}}]
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  providers  = { google = google.retrieval-service, google-beta = google-beta.retrieval-service }
  depends_on = [module.project-services-adcfood4]
}
module "database-postgresql" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v25.2.2"
  project_id                  = "adcfood4"
  region                      = "us-central1"
  name                        = "pg-ai-2003"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  db_name                     = "assistantdemo"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  database_deletion_policy    = "ABANDON"
  user_deletion_policy        = "ABANDON"
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.retrieval-service.service_account_id.email
    id    = module.retrieval-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  enable_google_ml_integration = true
  database_integration_roles   = ["roles/aiplatform.user"]
  providers                    = { google = google.database-postgresql, google-beta = google-beta.database-postgresql }
  depends_on                   = [module.project-services-adcfood4]
}
module "secret-manager" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.8.0"
  project_id  = "adcfood4"
  name        = "secret-2003"
  secret_data = module.database-postgresql.generated_user_password
  providers   = { google = google.secret-manager, google-beta = google-beta.secret-manager }
  depends_on  = [module.project-services-adcfood4]
}
module "vertex-ai" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id                  = "adcfood4"
  activate_apis               = ["aiplatform.googleapis.com"]
  disable_services_on_destroy = false
  providers                   = { google = google.vertex-ai, google-beta = google-beta.vertex-ai }
  depends_on                  = [module.project-services-adcfood4]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.3.0"
  project_id     = "adcfood4"
  location       = "us-central1"
  service_uris   = concat([module.frontend-service.apphub_service_uri], [module.retrieval-service.apphub_service_uri], [module.database-postgresql.apphub_service_uri])
  application_id = "gen-ai-rag-app"
}
module "project-services-adcfood4" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "adcfood4"
  disable_services_on_destroy = false
  activate_apis               = ["cloudkms.googleapis.com", "monitoring.googleapis.com", "cloudscheduler.googleapis.com", "workflows.googleapis.com", "essentialcontacts.googleapis.com", "serviceconsumermanagement.googleapis.com", "secretmanager.googleapis.com", "appengine.googleapis.com", "serviceusage.googleapis.com", "iam.googleapis.com", "accesscontextmanager.googleapis.com", "cloudbilling.googleapis.com", "servicenetworking.googleapis.com", "iamcredentials.googleapis.com", "run.googleapis.com", "compute.googleapis.com", "sqladmin.googleapis.com", "pubsub.googleapis.com", "admin.googleapis.com", "oslogin.googleapis.com", "billingbudgets.googleapis.com", "cloudresourcemanager.googleapis.com", "storage-api.googleapis.com"]
  providers                   = { google = google.project-services-adcfood4, google-beta = google-beta.project-services-adcfood4 }
}
