
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service.service_uri
}
output "retrieval-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.retrieval-service.service_uri
}
