
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
}
provider "google" {
  alias = "frontend-service"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "frontend-service"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google" {
  alias = "retrieval-service"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "retrieval-service"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google" {
  alias = "database-postgresql"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "database-postgresql"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google" {
  alias = "secret-manager"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "secret-manager"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google" {
  alias = "vertex-ai"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "vertex-ai"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google" {
  alias = "project-services-adcfood4"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
provider "google-beta" {
  alias = "project-services-adcfood4"
  default_labels = {
    goog-adc-tf-deployment = "adc"
  }
  billing_project       = "adcfood4"
  user_project_override = true
}
